# Generated by Django 4.2.16 on 2024-11-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_badge_alter_article_options_scope_article_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scope',
            field=models.ManyToManyField(related_name='scopes', through='articles.Scope', to='articles.badge'),
        ),
    ]
