# Generated by Django 4.1.1 on 2024-11-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=500)),
                ('release_date', models.CharField(max_length=50)),
                ('lte_exists', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
